language: python
python:
    - 3.3
    - 3.4
    - 3.5
install:
    - pip install .
    - pip install pytest==2.8.0
    - pip install coverage==4.0.0
    - pip install coveralls
script:
    - python3 tests/test_runner.py --data
after_success:
    - cd tests
    - coveralls
