environment:
    matrix:
    - PYTHON: C:\Python33
    - PYTHON: C:\Python34
    - PYTHON: C:\Python35
init:
    - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
    - git config --global core.autocrlf true
install:
    - pip install .
    - pip install pytest==2.8.*
    - pip install coverage==4.0.*
build: off
test_script:
    - python tests\test_runner.py
