environment:
    matrix:
    - PYTHON: C:\Python33
    - PYTHON: C:\Python34
init:
    - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
    - git config --global core.autocrlf true
install:
    - pip install .
    - pip install pytest
    - pip install coverage
build: off
test_script:
    - python tests\test_runner.py
